hero_chassis_controller/EffortChassisController:
  type: "hero_chassis_controller/EffortChassisController"
  joints:
    hero::left_front_wheel_joint:
      controller_name: "front_left_pid_controller_"
      pid:
        p: 100.0
        i: 0.5
        d: 0.0
        i_max: 10.0
        i_min: -10.0
        antiwindup: true
    hero::right_front_wheel_joint:
      controller_name: "front_right_pid_controller_"
      pid:
        p: 100.0
        i: 0.5
        d: 0.0
        i_max: 10.0
        i_min: -10.0
        antiwindup: true
    hero::left_back_wheel_joint:
      controller_name: "back_left_pid_controller_"
      pid:
        p: 100.0
        i: 0.5
        d: 0.0
        i_max: 10.0
        i_min: -10.0
        antiwindup: true
    hero::right_back_wheel_joint:
      controller_name: "back_right_pid_controller_"
      pid:
        p: 100.0
        i: 0.5
        d: 0.0
        i_max: 10.0
        i_min: -10.0
        antiwindup: true
hero_chassis_controller/MecanumWheelController:
  type: "mecanum_wheel_controller/MecanumWheelController"
  left_front_wheel_joint: "hero::left_front_wheel_joint"
  right_front_wheel_joint: "hero::right_front_wheel_joint"
  left_back_wheel_joint: "hero::left_back_wheel_joint"
  right_back_wheel_joint: "hero::right_back_wheel_joint"
  wheel_base: 0.5
  track_width: 0.5
  wheel_radius: 0.1
